
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-22T01:17:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "309fe0e5f98277ccbc96926591e26991aaf30489",
 "version": "v3.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
