# Generated by Django 4.1.2 on 2022-10-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField(null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('telemetry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_telemetry.webtelemetry')),
            ],
        ),
    ]
