# Generated by Django 4.1.2 on 2022-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telemetry', '0002_webquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtelemetry',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
