# Generated by Django 4.1.2 on 2022-10-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telemetry', '0006_alter_webtelemetry_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtelemetry',
            name='headers',
            field=models.TextField(default='headers'),
            preserve_default=False,
        ),
    ]
