
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-20T03:44:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e56a2469aff60d356125490866d0514ac95069f",
 "version": "1.17.1.post0.dev242"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
