# Generated by Django 2.2.26 on 2022-10-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellon', '0006_nameid_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionindex',
            name='saml_identifier',
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='mellon.UserSAMLIdentifier',
                verbose_name='SAML identifier',
            ),
        ),
    ]
