
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-20T04:08:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f6d0a7752a2e0cb8b9bd2535111d027d0c62df1",
 "version": "1.17.1.post0.dev245"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
