def cakes():
    return [
"7Up kage",
"Abrikos-chokoladekage – fedtfattig",
"Abrikosroulade",
"Adventskrans",
"After Eight Tærte",
"Ahornsirup tærte",
"Amaretto cheesecake",
"Amaretto Mousse cheesecake",
"Amarettokage",
"Amazin Raisinkage",
"Ambrosiatærte",
"American cheesecake",
"Amerikansk brownie",
"Amerikansk citronkage – fedtfattig",
"Amerikansk lagkage",
"Amerikanske småkager",
"Ananastærte",
"Andersines engleguf",
"Appelsinkage",
"Appelsinlagkage – fedtfattig",
"Appelsinmuffins",
"Appelsinsoufflé",
"Apple Pie",
"Astakage – fedtfattig",
"Bacardi Chokoladekage",
"Bagt cheesecake",
"Bagt chokoladecheesecake",
"Bagt æblekage – fedtfattig",
"Baileyscheesecake",
"Baileyschokoladecheesecake",
"Baileyskage",
"Banankage",
"Banankage – fedtfattig",
"Banankage med creme – fedtfattig",
"Banankage / muffins – fedtfattig",
"Bananlagkage",
"Bananmuffins – fedtfattig",
"Bananroulade",
"Banantærte",
"Bananyoughurtkage",
"Bedre end sex - kage",
"Bedstefarkage",
"Bedstefars skæg",
"Berliner Phannkuchen",
"Best Ever cheesecake",
"Bibelkage",
"Black Russiankage",
"Black Velvet",
"Bladankage",
"Blommelagkage",
"Blommetærte",
"Blondekage",
"Chantilly",
"Blød karameltærte",
"Blåbærcheesecake",
"Blåbærmuffins",
"Blåbærtærte",
"Bôche de Noel",
"Bondepige med slør",
"Borgmesterkrans",
"Bounty",
"Bounty kage",
"Brasiliansk kaffebanankage",
"Brasiliansk passionskage",
"Brombærchokoladetærte",
"Brunkagemuffins",
"Brunkager",
"Brunsviger",
"Brunsviger, fynsk",
"Bærroulade",
"Candy Bar Cookies",
"Cappuchinokysset cheesecake",
"Cappuchinomuffins",
"Cappuchinoroulade",
"Champagnekage",
"Charlotte Russe",
"Cheesecake med chokoladekrave",
"Cheesecake med jordbær",
"Cheesecake med",
"mandarin - fedtfattig",
"Cheesecakemuffins",
"Chilinødder Chokka Mocca",
"Chokolade Timbaler",
"Chokoladebanankage – fedtfattig",
"Chokoladebarmuffins",
"Chokoladebisquits",
"Chokoladeboller",
"Chokoladebomber",
"Chokoladecheesecake",
"Chokoladecookies",
"Chokoladecookies. - fedtfattig",
"Chokoladedaddelkage",
"Chokoladedukater",
"Chokoladeelskercheesecake",
"Chokoladegateau",
"Chokoladehindbærkage – fedtfattig",
"Chokoladekage",
"Chokoladekage – fedtfattig",
"Chokoladekage med creme",
"Chokoladekage med dadler – fedtfattig",
"Chokoladekage med valnødder",
"Chokoladekage Orange – fedtfattig",
"Chokoladekanin",
"Chokoladekokoskage",
"Chokoladekokoskage – fedtfattig",
"Chokoladelagkage",
"Chokolademarengs – fedtfattig",
"Chokolademokkaroulade",
"Chokolade - mokkatrøffel",
"Chokolademoussemarengskage",
"Chokolademoussetærte",
"Chokolademuffins",
"Chokolademuffins med bananer",
"Chokoladenougatkage",
"Chokoladenøddetærte",
"Chokoladericottacheesecake",
"Chokoladeroulade",
"Chokoladeroulade med Daim",
"Chokoladesmåkager – fedtfattig",
"Chokoladesoufflé",
"Chokoladetrøfler",
"Chokoladetærte med frisk frugt",
"Chokoladetærte med pecan",
"Chokoladetærte med sommerbær",
"Chokoladeyoughurtkage",
"Chokolate Chip Cookies",
"Chokolate Chip muffins",
"Chokolate Chunk Cookies",
"Christmas Cake",
"Citronhorn – fedtfattig",
"Citronmuffins",
"Citruskage",
"Coca Cola kage",
"Cognacdrøm",
"Cookies",
"Copipardilagkage",
"Cornflakescheesecake",
"Cornflakeskager",
"Crazykage",
"Daddellagkage",
"Daddeltærte",
"Daim kage",
"Daimmuffins",
"Daimmuffins",
"Death by chocolate",
"Den 7. himmel",
"Den du ved nok",
"Devils Food cake",
"Diddl’s honningjulekager",
"Diddls grønne lagkage",
"Died and went to heaven",
"Dobbeltbagte mandelkager",
"Doughnuts",
"Dronningen af Saba",
"Drømme",
"Drømmekage",
"Drømmekage – fedtfattig",
"Drømmeroulade",
"Egg Nog cheesecake",
"En dødssynd",
"Englelagkage",
"Eventyrlig moussetærte",
"Farfars mokkadrømme",
"Fastelavnsboller",
"Fastelavnsboller – fedtfattig",
"Favoritroulade",
"Festkage",
"Festlig kagemand",
"Festlige muffins",
"Figenroulade",
"Fin fransk chokoladepie",
"Finskbrød",
"Flødebollelagkage",
"Flødebollelagkage",
"Flødecheesecake",
"Fortune Cookies",
"Forårslagkage",
"Fragilitélagkage",
"Fransk chokoladetærte",
"Fruens drøm",
"Frugtlagkage",
"Frugtmuffins",
"Frugtpavlova",
"Frugtsoufflé",
"Frugttærte",
"Fuglereder",
"Færøsk æbleknas",
"Gallianokage",
"Gammeldags æblekage",
"Gateau D’ Apricot à la Orange",
"Genovatærte",
"Giftkage",
"Girafkage",
"Glade ansigter",
"Godsejerens bedste kage",
"Good 4 you cheesecake",
"Græskarmuffins",
"Grøn lagkage",
"Grønlænderlagkage",
"Guldbarre kage",
"Guldbarrekage",
"Guldkage",
"Guldkornskager",
"Gulerodcheesecake",
"Gulerodsappelsinkage – fedtfattig",
"Gulerodskage",
"Gulerodskage – fedtfattig",
"Gulerodsmuffins",
"Halloweenkage",
"Harvey Wallbanger kage",
"Hasselnøddemarengslagkage",
"Havregrynskager",
"Havregrynskugler",
"Havregrynsmakroner – fedtfattig",
"Havremuffins",
"Hawaiitærte",
"Herman",
"Himmerigsmundfulde",
"Hindbærcheesecake",
"Hindbærlagkage",
"Hindbærmuffins",
"Hindbærroulade",
"Hindbærsnitter",
"Hindbærsoufflé",
"Hindbærtærte",
"Hindbærtærte – fedtfattig",
"Hjertekage",
"Honey Crunch Tærte",
"Honningcheesecake",
"Honningcheesecake Praliné",
"Honningchokoladekage",
"Honningkage",
"Honningkage fra Thy – fedtfattig",
"Honningkagefigurer",
"Honningkagehjerter – fedtfattig",
"Honningkager – fedtfattig",
"Honningroulade",
"Hummingbirdkage",
"Hvedekage – fedtfattig",
"Hvid chokoladepærering",
"Hyggemuffins",
"Hysteostekage",
"Ingefærkage med flødeost",
"Irish Coffee kage",
"Irish Coffeeroulade",
"Irsk julekage",
"Irsk julekage – fedtfattig",
"Islagkage Fragilité",
"Islandsk chokoladekage",
"Islandsk lagkage",
"Islandske muffins",
"Italiensk chokolademandelrosinkage",
"Italiensk fødselsdagslagekage",
"Italiensk julekage",
"Italiensk mandelkage",
"Jordbær Daiquiri tærte",
"Jordbærlagkage",
"Jordbærrabarbertærte – fedtfattig",
"Jordbærroulade",
"Jordbærtærte",
"Jordbærtærte som fra bageren",
"Jordens bedste cheesecake",
"Jordskælvskage",
"Juelcookies",
"Julebakkelser",
"Julebiscotti",
"Julebiscotti – fedtfattig",
"Julebreve",
"Julebrownies",
"Julefrugtkage",
"Julehjerter",
"Julehonningkage",
"Julehorn – fedtfattig",
"Julekage med rom",
"Juleklumper",
"Julekrans",
"Julekranse",
"Julekys",
"Julelagkage",
"Julemuffins",
"Julens krydderkage",
"Juleroulade",
"Julespecier",
"Julestænger med marcipan",
"Juletræskager",
"Jødekager",
"Kaffebanankage",
"Kaffekys",
"Kaffetærte",
"Kagehus",
"Kagemand",
"Kagen fra Capri",
"Kahlua Cheesecake",
"Kahlua Mudslides",
"Kanelkage",
"Kanelkage – fedtfattig",
"Kanelkrans",
"Kanellagkage",
"Kanelmuffins",
"Kanelsnegle – fedtfattig",
"Kaneltærte med hvidtrøffel",
"Karamelcheesecake",
"Karamellagkage",
"Karamelsnitte med chokolade",
"Kartoffelkage",
"Kastanjecremeroulade",
"Kiksekage",
"Kirsebærcheesecake",
"Kirsebærlagkage",
"Kirsebærtærte",
"Kirsebærtærte – fedtfattig",
"Kiwitærte",
"Kniplingskager",
"Koklatter",
"Kokosbanankage Kokoscremekage",
"Kokoscremetærte",
"Kokosharmoni",
"Kokoskage",
"Kokoskage med kærnemælk",
"Kokosmakroner",
"Kokosmakroner – fedtfattig",
"Kokosmuffins",
"Kokosmuffins – fedtfattig",
"Kokostærte",
"Konfektkage",
"Konfektkage med hindbærskum",
"Konsulindens chokoladekage",
"Kransekage",
"Kransekagekonfekt",
"Karamelkage",
"Krydderkage – fedtfattig",
"Kryddermuffins",
"Krydret julehjerte",
"Krydret julehjerte",
"Kvarkkage",
"Kvarklagkage – fedtfattig",
"Kys og klap",
"Kærlighedskranse",
"Kærnemælkscheesecake",
"Lady Hamiltonkage",
"Ladyfingers",
"Lagkage med rom og rosin",
"Lagkagetog",
"Likørkaffecheesecake",
"Likørmokkakage",
"Lime Pie",
"Limesoufflé",
"Linser",
"Luxusroulade",
"M & M’s kager",
"Makronkager",
"Mandelkager",
"Mandellagkage med nougat",
"Mandelmuffins",
"Mandeltærte",
"Mandeltærte med mousse",
"Mangotærte",
"Marcipanmuffins",
"Marcipanpæretærte",
"Marcipantærte",
"Marengskage",
"Marengskager – fedtfattig",
"Marengskurv",
"Marengslagkage",
"Marengsreder med chokolademousse",
"Marengsroulade",
"Marmeladekage",
"Marmoreret chokoladekage",
"Marmorkage",
"Marsbarguf",
"Marshmallows",
"Matadormixlagkage",
"Melontærte",
"Melt in your mouth",
"Mickey Mousekage",
"Midsommertærte",
"Mile High chokoladekage",
"Milky Way kage",
"Milky Way tærte",
"Mississippi Mud Pie",
"Mokkacheesecake",
"Mokkadrømme",
"Mokkaroulade",
"Mokkasoufflé",
"Mors dags kage",
"Mumsekage",
"New York cheesecake",
"Nonna Marias frugttærte",
"Nougatnøddelagkage",
"Nougatroulade",
"Nutellaroulade",
"Nødderoulade",
"Nøddesnitter",
"Oldemors Brunkager",
"Ostechokoladekage",
"Othellolagkage",
"Pandekagetærte",
"Paradiskage",
"Pariserlagkage",
"Passionscheesecake",
"Pavlova",
"Peach Pie",
"Peanut cheesecake",
"Peanutbutterbar",
"Peanutbuttermuffins",
"Peanutchokoladekage",
"Peanutskage",
"Pebernødder",
"Pecan cheesecake",
"Pepsikage",
"Pina Colada tærte",
"Pisk og bag kage",
"Pistaciekage",
"Pistaciekranse",
"Plumkage",
"Popcornkage",
"Portvinstærte",
"Pradisroulade",
"Pralinémarengstærte",
"Prins Henriks Dur Mou",
"Pumpkin Pie",
"Pumpkin Pie muffins",
"Pære - ingefær cheesecake",
"Pæretærte",
"Pæretærte – fedtfattig",
"Påskeliljekage",
"Rabarberabrikostærte",
"Rabarberkage – fedtfattig",
"Rabarberlagkage",
"Rabarbertærte",
"Red Velvet",
"Ribskage – fedtfattig",
"Richiarelli",
"Ricottatærte med chokolade",
"Rocky Road",
"Rom og rosinkage",
"Rom og rosintrøfler",
"Rosinmuffins",
"Roulade med is – fedtfattig",
"Rubinsteinkage",
"Rugbrødslagkage",
"Rugbrødstærte",
"Rutebiler",
"Rutebilslagkage",
"Sachertorte",
"Safranmuffins",
"Sarah Bernard kager",
"Schnickerskage",
"Screwdriverkage",
"Sex in a pan",
"Siciliansk cheesecake",
"Sirupskage",
"Sirupskage – fedtfattig",
"Sirupslagkage",
"Skilpaddekage",
"Skovbærtærte",
"Skovlagkage",
"Slankekager, 4 forskellige",
"Smørkage",
"Små chokoladetærter",
"Snebolde",
"Snickers snacks",
"Snickerskage",
"Solbærcheesecake",
"Solbærtærte",
"Sort magi kage",
"Sprød jordbærtærte",
"Squashkage",
"Squashmuffins",
"St.Emillion au Chokolat",
"Stikkelsbærtærte",
"Stollen",
"Sukkerbrødsbunde – fedtfattig",
"Swartzwalderkage",
"Sydstatskagen",
"Syltetøjslagkage",
"Syltetøjsroulade",
"Søde juleringe",
"Sødt hjerte",
"Søndagskringle",
"Thurøkage",
"Tia Maria",
"Cheesecake",
"Tigerkage",
"Tiramisu",
"Tiramisu – fedtfattig",
"Tiramisucheesecake",
"Tiramisuroulade",
"Tivolis lækkeri",
"Toffeetærte",
"Tropisk cheesecake",
"Trøffelkage med kirsebær",
"TUC kage",
"Tærte Imperial",
"Valentines Cookies",
"Valentines day tærte",
"Valentineskage",
"Valnøddedrøm",
"Valnøddekage med mokka",
"Valnøddemuffins",
"Valnødderoulade",
"Valnøddetærte",
"Vancouverkager",
"Vandbakkelser",
"Vandmelonkage",
"Vaniliekranse",
"Vanilliekranse",
"Vidunderlagkage",
"Weekendkager – fedtfattig",
"Whiskeykage",
"Yankiebar guf",
"Youghurtkage",
"Æblecitronkage – fedtfattig",
"Æblehorn – fedtfattig",
"Æblekage – fedtfattig",
"Æblekage med mandeldej",
"Æbleknas – fedtfattig",
"Æblemodkage",
"Æbletranebærkage – fedtfattig",
"Ølkage" ]