
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-17T04:46:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c368111f0331caed17218cde786fd95c5bd788b1",
 "version": "1.17.1.post0.dev202"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
