#!/usr/bin/env python3

# Bundle class, pylint: disable=too-few-public-methods
class Bundle:

    # Aliases
    ALIAS = 'gcil'

    # Names
    NAME = 'gitlabci-local'

    # Configurations
    CONFIGURATION = '.gitlab-ci.yml'

    # Sources
    REPOSITORY = 'https://gitlab.com/AdrianDC/gitlabci-local'

    # Releases
    RELEASE_FIRST_TIMESTAMP = 1579337311

    # Environment
    ENV_COMMIT_SHA = 'CI_COMMIT_SHA'
    ENV_COMMIT_REF_NAME = 'CI_COMMIT_REF_NAME'
    ENV_COMMIT_REF_SLUG = 'CI_COMMIT_REF_SLUG'
    ENV_COMMIT_SHORT_SHA1 = 'CI_COMMIT_SHORT_SHA'
    ENV_ENGINE = 'CI_LOCAL_ENGINE'
    ENV_ENGINE_NAME = 'CI_LOCAL_ENGINE_NAME'
    ENV_GIT_BINARY_PATH = 'GIT_BINARY_PATH'
    ENV_HISTORIES_DURATION_FAKE = 'CI_LOCAL_HISTORIES_DURATION_FAKE'
    ENV_LOCAL = 'CI_LOCAL'
    ENV_NETWORK = 'CI_LOCAL_NETWORK'
    ENV_NO_GIT_SAFETIES = 'CI_LOCAL_NO_GIT_SAFETIES'
    ENV_NO_SCRIPT_FAIL = 'CI_LOCAL_NO_SCRIPT_FAIL'
    ENV_PODMAN_BINARY_PATH = 'PODMAN_BINARY_PATH'
    ENV_PROJECT_NAME = 'CI_PROJECT_NAME'
    ENV_PROJECT_NAMESPACE = 'CI_PROJECT_NAMESPACE'
    ENV_UPDATES_DAILY = 'CI_LOCAL_UPDATES_DAILY'
    ENV_UPDATES_DISABLE = 'CI_LOCAL_UPDATES_DISABLE'
    ENV_UPDATES_FAKE = 'CI_LOCAL_UPDATES_FAKE'
    ENV_UPDATES_OFFLINE = 'CI_LOCAL_UPDATES_OFFLINE'
    ENV_VERSION_FAKE = 'CI_LOCAL_VERSION_FAKE'
    ENV_WINPTY = 'CI_LOCAL_WINPTY'
    ENV_WINPTY_PATH = 'WINPTY_BINARY_PATH'
