
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-20T15:55:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d2c7b6a3e616c1567221c50fc8994a4343b5de1",
 "version": "2022.10.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
