
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-18T12:00:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0002325c0ed063d7cb90e549eadaf86e8dba4b24",
 "version": "0.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
