
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-18T17:55:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "acc96a5dae9e99a107fdeb9d49611bc45706f707",
 "version": "v22.12.00a221020"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
