
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-17T21:50:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c82f86f0c922b89c4d7af5278e83a0f5bd5f0114",
 "version": "0.2.32.post0.dev22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
