
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-16T17:13:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dd4dbeb54fe9b48db92e6eccb56753784792450",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
