# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pfs.api.v1 import job_pb2 as pfs_dot_api_dot_v1_dot_job__pb2


class JobServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchJobState = channel.unary_stream(
                '/pfs.api.v1.JobService/WatchJobState',
                request_serializer=pfs_dot_api_dot_v1_dot_job__pb2.WatchJobStateRequest.SerializeToString,
                response_deserializer=pfs_dot_api_dot_v1_dot_job__pb2.WatchJobStateResponse.FromString,
                )


class JobServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WatchJobState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchJobState': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchJobState,
                    request_deserializer=pfs_dot_api_dot_v1_dot_job__pb2.WatchJobStateRequest.FromString,
                    response_serializer=pfs_dot_api_dot_v1_dot_job__pb2.WatchJobStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pfs.api.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WatchJobState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pfs.api.v1.JobService/WatchJobState',
            pfs_dot_api_dot_v1_dot_job__pb2.WatchJobStateRequest.SerializeToString,
            pfs_dot_api_dot_v1_dot_job__pb2.WatchJobStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
