# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pfs.api.v1 import source_connection_pb2 as pfs_dot_api_dot_v1_dot_source__connection__pb2


class SourceConnectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSourceConnections = channel.unary_unary(
                '/pfs.api.v1.SourceConnectionService/GetSourceConnections',
                request_serializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.GetSourceConnectionsRequest.SerializeToString,
                response_deserializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.GetSourceConnectionsResponse.FromString,
                )
        self.CreateSourceConnection = channel.unary_unary(
                '/pfs.api.v1.SourceConnectionService/CreateSourceConnection',
                request_serializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.CreateSourceConnectionRequest.SerializeToString,
                response_deserializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.CreateSourceConnectionResponse.FromString,
                )
        self.UpdateSourceConnection = channel.unary_unary(
                '/pfs.api.v1.SourceConnectionService/UpdateSourceConnection',
                request_serializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.UpdateSourceConnectionRequest.SerializeToString,
                response_deserializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.UpdateSourceConnectionResponse.FromString,
                )


class SourceConnectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSourceConnections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSourceConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSourceConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SourceConnectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSourceConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSourceConnections,
                    request_deserializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.GetSourceConnectionsRequest.FromString,
                    response_serializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.GetSourceConnectionsResponse.SerializeToString,
            ),
            'CreateSourceConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSourceConnection,
                    request_deserializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.CreateSourceConnectionRequest.FromString,
                    response_serializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.CreateSourceConnectionResponse.SerializeToString,
            ),
            'UpdateSourceConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSourceConnection,
                    request_deserializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.UpdateSourceConnectionRequest.FromString,
                    response_serializer=pfs_dot_api_dot_v1_dot_source__connection__pb2.UpdateSourceConnectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pfs.api.v1.SourceConnectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SourceConnectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSourceConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pfs.api.v1.SourceConnectionService/GetSourceConnections',
            pfs_dot_api_dot_v1_dot_source__connection__pb2.GetSourceConnectionsRequest.SerializeToString,
            pfs_dot_api_dot_v1_dot_source__connection__pb2.GetSourceConnectionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSourceConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pfs.api.v1.SourceConnectionService/CreateSourceConnection',
            pfs_dot_api_dot_v1_dot_source__connection__pb2.CreateSourceConnectionRequest.SerializeToString,
            pfs_dot_api_dot_v1_dot_source__connection__pb2.CreateSourceConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSourceConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pfs.api.v1.SourceConnectionService/UpdateSourceConnection',
            pfs_dot_api_dot_v1_dot_source__connection__pb2.UpdateSourceConnectionRequest.SerializeToString,
            pfs_dot_api_dot_v1_dot_source__connection__pb2.UpdateSourceConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
