
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-20T06:45:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7b16072c2425baef3194a224f39c12fd252c5ab",
 "version": "1.17.1.post0.dev266"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
