
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-19T11:14:35-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e358d132757da3e47fafaea7420803eed102b19b",
 "version": "2022.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
