
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-19T12:54:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d34b2ef2305dd4f328e3cac527a437582226e12",
 "version": "2022.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
