depends = ('ITKPyBase', 'ITKStatistics', 'ITKImageSources', 'ITKCommon', )
templates = (  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerSS2', True, 'signed short, 2'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerUC2', True, 'unsigned char, 2'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerUS2', True, 'unsigned short, 2'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerF2', True, 'float, 2'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerD2', True, 'double, 2'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerSS3', True, 'signed short, 3'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerUC3', True, 'unsigned char, 3'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerUS3', True, 'unsigned short, 3'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerF3', True, 'float, 3'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerD3', True, 'double, 3'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerSS4', True, 'signed short, 4'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerUC4', True, 'unsigned char, 4'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerUS4', True, 'unsigned short, 4'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerF4', True, 'float, 4'),
  ('CLEDataManager', 'itk::CLEDataManager', 'itkCLEDataManagerD4', True, 'double, 4'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerSS2', True, 'signed short, 2'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerUC2', True, 'unsigned char, 2'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerUS2', True, 'unsigned short, 2'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerF2', True, 'float, 2'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerD2', True, 'double, 2'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerSS3', True, 'signed short, 3'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerUC3', True, 'unsigned char, 3'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerUS3', True, 'unsigned short, 3'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerF3', True, 'float, 3'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerD3', True, 'double, 3'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerSS4', True, 'signed short, 4'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerUC4', True, 'unsigned char, 4'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerUS4', True, 'unsigned short, 4'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerF4', True, 'float, 4'),
  ('CLEImageDataManager', 'itk::CLEImageDataManager', 'itkCLEImageDataManagerD4', True, 'double, 4'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageSS2', True, 'signed short, 2'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageUC2', True, 'unsigned char, 2'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageUS2', True, 'unsigned short, 2'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageF2', True, 'float, 2'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageD2', True, 'double, 2'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageSS3', True, 'signed short, 3'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageUC3', True, 'unsigned char, 3'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageUS3', True, 'unsigned short, 3'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageF3', True, 'float, 3'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageD3', True, 'double, 3'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageSS4', True, 'signed short, 4'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageUC4', True, 'unsigned char, 4'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageUS4', True, 'unsigned short, 4'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageF4', True, 'float, 4'),
  ('CLEImage', 'itk::CLEImage', 'itkCLEImageD4', True, 'double, 4'),
)
factories = ()
