# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/agents/v1/streams_agent_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from strmprivacy.api.entities.v1 import entities_v1_pb2 as strmprivacy_dot_api_dot_entities_dot_v1_dot_entities__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0strmprivacy/api/agents/v1/streams_agent_v1.proto\x12\x19strmprivacy.api.agents.v1\x1a-strmprivacy/api/entities/v1/entities_v1.proto\"\x13\n\x11GetStreamsRequest\"[\n\x12GetStreamsResponse\x12\x45\n\x10\x65xtended_streams\x18\x01 \x03(\x0b\x32+.strmprivacy.api.entities.v1.ExtendedStream2\x80\x01\n\x13StreamsAgentService\x12i\n\nGetStreams\x12,.strmprivacy.api.agents.v1.GetStreamsRequest\x1a-.strmprivacy.api.agents.v1.GetStreamsResponseBc\n\x1cio.strmprivacy.api.agents.v1P\x01ZAgithub.com/strmprivacy/api-definitions-go/v2/api/agents/v1;agentsb\x06proto3')



_GETSTREAMSREQUEST = DESCRIPTOR.message_types_by_name['GetStreamsRequest']
_GETSTREAMSRESPONSE = DESCRIPTOR.message_types_by_name['GetStreamsResponse']
GetStreamsRequest = _reflection.GeneratedProtocolMessageType('GetStreamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMSREQUEST,
  '__module__' : 'strmprivacy.api.agents.v1.streams_agent_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.agents.v1.GetStreamsRequest)
  })
_sym_db.RegisterMessage(GetStreamsRequest)

GetStreamsResponse = _reflection.GeneratedProtocolMessageType('GetStreamsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTREAMSRESPONSE,
  '__module__' : 'strmprivacy.api.agents.v1.streams_agent_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.agents.v1.GetStreamsResponse)
  })
_sym_db.RegisterMessage(GetStreamsResponse)

_STREAMSAGENTSERVICE = DESCRIPTOR.services_by_name['StreamsAgentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034io.strmprivacy.api.agents.v1P\001ZAgithub.com/strmprivacy/api-definitions-go/v2/api/agents/v1;agents'
  _GETSTREAMSREQUEST._serialized_start=126
  _GETSTREAMSREQUEST._serialized_end=145
  _GETSTREAMSRESPONSE._serialized_start=147
  _GETSTREAMSRESPONSE._serialized_end=238
  _STREAMSAGENTSERVICE._serialized_start=241
  _STREAMSAGENTSERVICE._serialized_end=369
# @@protoc_insertion_point(module_scope)
