from .typing import LikePath as LikePath
from .webdav import webdav_download_all as webdav_download_all

def download_bimcv_covid19_positive(root: LikePath): ...
def download_bimcv_covid19_negative(root: LikePath): ...
