
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-21T09:59:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "feeccf8e12bead6dbc26901a6c41af7fa3078550",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
