
# This file was generated by 'versioneer.py' (0+bootstrap) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-19T08:04:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "759b365c34a46d34d5d4a3531b39beac25b3fb96",
 "version": "0.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
