
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-21T23:01:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "19490f8ba2dff6254fc947f70343af2cd8f30b41",
 "version": "0.2.35.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
