# Generated by Django 4.1.1 on 2022-10-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_group',
            field=models.ManyToManyField(to='menu.menugroup'),
        ),
    ]
