
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-14T17:46:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7ff283de3abe3b570d24d34c8817e76242b892d",
 "version": "2.8.7.dev20221017"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
