
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-18T10:28:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "70f9bb2e0a40c982e8475aa802dd65056d489cb4",
 "version": "v0.0.1-beta.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
