
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-17T06:07:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d86e35402634a6e6ca5aeb165b3ea4961bcae0c",
 "version": "1.17.1.post0.dev214"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
