VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('19')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('26')
MAJOR_VERSION = 1
MINOR_VERSION = 7
PATCH_VERSION = 202210190926
version_date = '2022/10/19 09:26'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
