import pandas as pd
import typing as tp
from . import tools as tools
from .typing import BIMCVCOVID19Root as BIMCVCOVID19Root, Labels as Labels, LikePath as LikePath, SeriesRawPath as SeriesRawPath, Session as Session, Subject as Subject, Test as Test
from .webdav import webdav_download_all as webdav_download_all
from pathlib import Path

def download_bimcv_covid19_positive(root: LikePath): ...
def download_bimcv_covid19_negative(root: LikePath): ...
def subjects_dataframe_bimcv_covid19_positive(root: LikePath) -> pd.DataFrame: ...
def subjects_bimcv_covid19_positive(root: LikePath) -> tp.List[Subject]: ...
def read_sessions_bimcv_covid19_positive(root_bimcv_covid19) -> tp.List[Session]: ...
def iterate_sessions_bimcv_covid19_positive(root: LikePath) -> tp.Iterator[Path]: ...
def group_series_files_by_name(session_root: Path) -> tp.Iterator[SeriesRawPath]: ...
def extract_tests(dataframe: pd.DataFrame) -> tp.Dict[str, tp.List[Test]]: ...
def extract_labels(dataframe: pd.DataFrame) -> tp.Dict[str, Labels]: ...
def tests_dataframe_bimcv_covid19_positive(root: LikePath) -> pd.DataFrame: ...
def tests_bimcv_covid19_positive(root: LikePath) -> tp.Dict[str, tp.List[Test]]: ...
def labels_dataframe_bimcv_covid19_positive(root: LikePath) -> pd.DataFrame: ...
def labels_bimcv_covid19_positive(root: LikePath) -> tp.Dict[str, Labels]: ...
def extract_bimcv_covid19_positive(root: LikePath): ...
