
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-19T14:19:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7171c842d0f2f22cd95e4ee36004c99fa7b448cc",
 "version": "v0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
