
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-17T15:02:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c6ac480897d647d450f1d9092771455d38e1a56",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
