
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-16T16:31:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "05d917a3e824904dd6452c9d330d5df5f53d32f2",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
