
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-22T11:52:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a507a8ffd4135b0ec913c808b6d62e8e99dae1b2",
 "version": "2022.10.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
