
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-17T14:42:23-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "75b99b65f679127232233e95b516cde0f972c1a0",
 "version": "v0.0.1-alpha.post0.dev0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
