# Generated by Django 3.2.13 on 2022-06-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_alter_logentry_additional_data'),
        ('devind_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntrySession',
            fields=[
                ('log_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auditlog.logentry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devind_core.session')),
            ],
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
