
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-21T10:49:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "efe8202a596c0b1378a1182bcd2771dbbda6e7f1",
 "version": "0.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
