
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-17T08:18:08-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "11303e63413d2d3ff2165a076efd4800bb835032",
 "version": "1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
