
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-21T09:58:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3d9e3dd9c48975c8ec5c64d52491e6377247eb4",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
