
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-19T11:57:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f9262f7eabe40316bdafc587ea2fe13021f0a76",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
