
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-17T14:41:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c66df52c9c2e04594cc7226708fbd8d7ba7722a",
 "version": "2.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
